export const PAYMENT_TERMS = [
  "100% before dispatch of material again proforma invoice",
  "50% before dispatch against proforma invoice and balance 50% at time of dispatch against Invoice & Eway bill",
  "50% before dispatch of materials against proforma invoice and balance 50% on delivery of the material",
  "50% before dispathc of material against Invoice and balance 50% on delivery of the material",
  "100% on delivery of the material",
];

export const FREQUENCIES = ["Once", "Monthly"];
export const CHARGE_TYPES = ["Included", "Extra", "Not applicable"];

export const PRODUCT_UNIT = [
  "Bottle/Bottles",
  "Container/Containers",
  "Bale",
  "Billions Of Unit",
  "Buckle",
  "Bunch",
  "Bundle",
  "Dozen",
  "Great Gross",
  "Gross",
  "Gross Yard",
  "Kiloliter",
  "Metric Ton",
  "Number",
  "Quintal",
  "Meter",
  "Tablet",
  "Ten Gross",
  "Thousand",
  "Tube",
  "US Gallon",
  "Yard",
  "Kit/Kits",
  "Vial/Vials",
  "Strip/Strips",
  "Foot/Feet",
  "Meter/Meters",
  "Millimeter/Millimeters",
  "Pole/Poles",
  "Twenty-Foot Container",
  "Short Ton/Short Tons",
  "Cubic Foot/Cubic Feet",
  "Cubic Meter/Cubic Meters",
  "Cubic Yard/Cubic Yards",
  "Dram/Drams",
  "Gill/Gills",
  "Milliliter/Milliliters",
  "Bushel/Bushels",
  "Pound/Pounds",
  "Square Yard/Square Yards",
  "Acre/Acres",
  "Ampere/Amperes",
  "Kiloampere/Kiloamperes",
  "Kiloohm/Kiloohms",
  "Kilovolt/Kilovolts",
  "Kilowatt/Kilowatts",
  "Milliampere/Milliamperes",
  "Milliohm/Milliohm,",
  "Millivolt/Millivolts",
  "Milliwatt/Milliwatts",
  "Ohm/Ohms",
  "Kilohertz",
  "Megahertz",
  "Quart/Quarts",
  "Barrel/Barrels",
  "Fluid Ounce/Fluid Ounces",
  "Gallon/Gallons",
  "Liter/Liters",
  "Gram/Grams",
  "Kilograms/Kilograms",
  "Long Ton/Long Tons",
  "Metric Ton/Metric Tons",
  "Milligram/Milligrams",
  "Stone/Stones",
  "Ton/Tons",
  "Tonne/Tonnes",
  "Unit/Units",
  "Volt/Volts",
  "Watt/Watts",
  "Wp",
  "Hertz",
  "Milihertz",
  "Centimeter/Centimeters",
  "Chain/Chains",
  "Forty-Foot Container",
  "Furlong/Furlongs",
  "Inch/Inches",
  "Yard/Yards",
  "Carat/Carats",
  "Ounce/Ounces",
  "Bag/Bags",
  "Box/Boxes",
  "Carton/Cartons",
  "Case/Cases",
  "Pack/Packs",
  "Pair/Pairs",
  "Pallet/Pallets",
  "Parcel/Parcels",
  "Perch/Perches",
  "Piece/Pieces",
  "Paint/Paints",
  "Plant/Plants",
  "Rod/Rods",
  "Roll/Rolls",
  "Set/Sets",
  "Sheet/Sheets",
  "Strand/Strands",
  "Hectare/Hectares",
  "Square Centimeters",
  "Square Foot/Square Foots",
  "Square Inch/Square Inches",
  "Square Meter/Square Meters",
  "Square Mile/Square Miles",
  "Gross",
  "Dozen/Dozens",
  "Tray/Trays",
  "Grain/Grains",
  "Quarter/Quarters",
  "Degrees Celsius",
  "Degrees Fahrenheit",
  "Kilometer/Kilometers",
  "Mile/Miles",
  "Nautical Mile/Nautical Miles",
  "Cubic Centimeters",
];

export const SUB_CATEGORIES = {
  solid: [
    {
      title: "Animal Tallow",
      desc: "a rendered form of animal fat used in the production of various products, including soap, candles, cosmetics, and lubricants",
      id: "animal_tallow",
    },
    {
      title: "Chicken Tallow",
      desc: "a rendered form of chicken fat that is commonly used in cooking, as well as in the production of various products, including soap, candles, and cosmetics",
      id: "chicken_tallow",
    },
    {
      title: "Palm Stearin",
      desc: "a solid fraction of palm oil commonly used in the food industry for its high melting point and semi-solid texture",
      id: "palm_stearin",
    },
    {
      title: "PP/HDPE Waste",
      desc: "a highly recyclable discarded materials made of Polypropylene (PP) and High-Density Polyethylene (HDPE) plastics",
      id: "pp_hdpe_waste",
    },
    { title: "LDP/MHW", desc: "Solid Fuel", id: "ldp_mhw" },
    {
      title: "Tyre Waste",
      desc: "can be recycled or repurposed into various products, including construction materials,fuel, and rubber products such as playground surfaces and asphalt.",
      id: "tyre_waste",
    },
    {
      title: "Saw Dust",
      desc: "fine wood particles can be used for various applications, including as a fuel source, animal bedding, and as a raw material in the production of particleboard, paper, and biofuels.",
      id: "saw_dust",
    },
    {
      title: "Wood Chips",
      desc: " used for various applications, including as a fuel source, animal bedding, composting, landscaping, and as a raw material in the production of paper and engineered wood products.",
      id: "wood_chips",
    },
    {
      title: "Rise Husk",
      desc: "refers to the protective outer layer of rice grains repurposed for various applications, including as a fuel source, animal bedding, insulation, and in the production of building materials and composites",
      id: "rise_husk",
    },
    {
      title: "Coffee Husk",
      desc: "a byproduct of the coffee industry used as a raw material for various products",
      id: "coffee_husk",
    },
    {
      title: "Ground Nut Cell",
      desc: "a renewable resource used as a feedstock , food , filler in fertilizer and even in bio filter carriers .",
      id: "ground_nut_cell",
    },
    {
      title: "Soya Husk",
      desc: "can be repurposed for various applications, including as animal feed, fertilizer, and as a raw material in the production of paper and particleboard",
      id: "soya_husk",
    },
    {
      title: "Carbon Black",
      desc: "a fine powder made from carbon widely used material in various industrial applications, including as a reinforcing agent in rubber products",
      id: "carbon_black",
    },
    {
      title: "Bio-Mass Pallets",
      desc: " Biomass pellets used as a fuel source in heating systems, such as pellet stoves, furnaces, and boilers",
      id: "bio_mass_pallets",
    },
    {
      title: "Starch Based Raw Materials",
      desc: "Starch-based raw materials are commonly used in the production of various biodegradable products, such as packaging materials, disposable cutlery, and food containers.",
      id: "starch_based_raw_materials",
    },
    {
      title: "RDF (Refuse Derived Fuel)",
      desc: "a type of fuel that is produced by sorting and processing municipal solid waste (MSW) and other types of non-hazardous waste materials",
      id: "rdf_refuse_derived_fuel",
    },
    {
      title: "Biomass Briquettes/Bio Coal",
      desc: "also known as bio coal, are compressed blocks of organic materials, such as sawdust, agricultural waste, and other biomass materials",
      id: "biomass_briquettes_bio_coal",
    },
    {
      title: "Other Bio Mass",
      desc: " organic materials derived from various sources, including agricultural waste, forest residue, algae, and other forms of biomass",
      id: "other_bio_mass",
    },
  ],
  liquid: [
    {
      title: "High Speed Diesel",
      desc: "A refined petroleum product with a higher cetane number and low sulfur content, designed for use in high-speed diesel engines.",
      id: "high_speed_diesel",
    },
    {
      title: "Bio Diesel (B-100)",
      desc: "A renewable, clean-burning diesel alternative made from natural, biodegradable sources.",
      id: "bio_diesel_b_100",
    },
    {
      title: "LDO",
      desc: "A low-grade fuel oil commonly used for boilers, furnaces, and other equipment in industrial and agricultural applications.",
      id: "ldo",
    },
    {
      title: "Bio-LDO",
      desc: "A renewable alternative to traditional LDO made from natural, biodegradable sources",
      id: "bio_ldo",
    },
    {
      title: "Furnace Oil ",
      desc: "A dark, viscous residual fuel oil , commonly used for high-heat applications",
      id: "furnace_oil_",
    },
    {
      title: "Base Oil",
      desc: "Refined petroleum product used as a base component for manufacturing lubricating oils and greases",
      id: "base_oil",
    },
    {
      title: "Bitumen",
      desc: "Bitumen is a sticky, black, highly viscous liquid for road construction, roofing, and waterproofing",
      id: "bitumen",
    },
    {
      title: "UCO",
      desc: "UCO a feedstock for biodiesel production.",
      id: "uco",
    },
    {
      title: "MTO",
      desc: "Methanol-to-Olefins used for plastics production.",
      id: "mto",
    },
    {
      title: "MTO Cut",
      desc: "MTO Cut , a product obtained by the catalytic conversion of methanol for plastics production",
      id: "mto_cut",
    },
    {
      title: "MHO",
      desc: "vegetable oil extracted from the seeds of the Mahua tree.",
      id: "mho",
    },
    {
      title: "Bio-Ethanol",
      desc: "A renewable fuel made from plant materials, through a process of fermentation and distillation.",
      id: "bio_ethanol",
    },
    {
      title: "Bio-Furnace Oil",
      desc: "Bio-Furnace Oil is a type of fuel produced from renewable sources,a substitute for traditional furnace oil",
      id: "bio_furnace_oil",
    },
    {
      title: "Bio- Fuel Additives",
      desc: "Bio- Fuel Additives are substances added to biofuels to improve their performance, reduce emissions, and enhance their storage stability",
      id: "bio_fuel_additives",
    },
    {
      title: "Acid Oil",
      desc: " A byproduct of vegetable oil refining that is rich in free fatty acids and has various industrial applications",
      id: "acid_oil",
    },
    {
      title: "Other Vegetable Oil",
      desc: "Other vegetable oil refers to any oil extracted from plants or seeds that is used for cooking, baking, frying, and various industrial applications",
      id: "other_vegetable_oil",
    },
    {
      title: "Bio-Lubricants",
      desc: "environmentally friendly lubricants made from renewable resources",
      id: "bio_lubricants",
    },
    {
      title: "Lubricants",
      desc: "Substance to reduce friction",
      id: "lubricants",
    },
    {
      title: "New Bitumen",
      desc: "An alternative sources of fatty acids used for production of production of a variety of products",
      id: "new_bitumen",
    },
  ],
  gas: [
    {
      title: "Bio-CNG/CBG",
      desc: "a renewable, eco-friendly fuel produced by the anaerobic digestion of organic waste",
      id: "bio_cng_cbg",
    },
    {
      title: "CNG",
      desc: "Cng used as a substitute for fossil fuels in transportation, cooking, and heating applications, reducing greenhouse gas emissions and promoting sustainable waste management.",
      id: "cng",
    },
    {
      title: "LNG",
      desc: "a clear, odorless, and non-toxic liquid form of natural gas that used as a fuel for transportation, electricity generation, and industrial processes, due to its high energy density",
      id: "lng",
    },
    {
      title: "Green Hydrogen",
      desc: " a sustainable energy source for various applications, including transportation, heating, and electricity generation.",
      id: "green_hydrogen",
    },
  ],
};
